# Generated by Django 2.1 on 2019-04-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='history',
            new_name='keyword',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='history',
            field=models.CharField(default='', max_length=128, verbose_name='搜索历史'),
        ),
    ]
