# Generated by Django 2.1 on 2019-04-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190408_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='history_word2vec',
            new_name='keyword_word2vec',
        ),
    ]
