# Generated by Django 2.1 on 2019-04-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190408_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord2Vec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', max_length=128, verbose_name='搜索历史关键词')),
                ('keyword_word2vec', models.CharField(default='', max_length=256, verbose_name='关键词word2vec')),
            ],
            options={
                'verbose_name': '关键词word2vec',
                'verbose_name_plural': '关键词word2vec',
            },
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
